name: Publish Artifacts
on:
  push:
    tags:
        - 'v*'
  workflow_dispatch:


jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    environment: maven-central
    steps:
      - uses: actions/checkout@v7
        with: { fetch-depth: 1 }

      - run: ./mill mill.javalib.SonatypeCentralPublishModule/ --publishArtifacts __.publishArtifacts
        env:
          MILL_PGP_PASSPHRASE:    ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}